### ISSUE TITLE
NPE for git-less project

### ISSUE THREAD

**Issue by twwd** [thomasrepnik/idea-commit-prefix-plugin#11]
In a project without `git`, I've got the following NPE in IntelliJ IDEA 2021.1 (Ultimate Edition), Build #IU-211.6693.111
```
java.lang.NullPointerException
	at ch.repnik.intellij.CommitPrefixCheckinHandler.extractBranchName(CommitPrefixCheckinHandler.java:144)
	at ch.repnik.intellij.CommitPrefixCheckinHandler.getNewCommitMessage(CommitPrefixCheckinHandler.java:56)
	at ch.repnik.intellij.CommitPrefixCheckinHandler.updateCommitMessage(CommitPrefixCheckinHandler.java:44)
	at ch.repnik.intellij.CommitPrefixCheckinHandler.<init>(CommitPrefixCheckinHandler.java:40)
	at ch.repnik.intellij.GitBaseCheckinHandlerFactory.createVcsHandler(GitBaseCheckinHandlerFactory.java:18)
	at com.intellij.openapi.vcs.checkin.VcsCheckinHandlerFactory.createVcsHandler(VcsCheckinHandlerFactory.kt:27)
	at com.intellij.openapi.vcs.checkin.VcsCheckinHandlerFactory.createHandler(VcsCheckinHandlerFactory.kt:16)
	at com.intellij.vcs.commit.AbstractCommitWorkflow$Companion.getCommitHandlers(AbstractCommitWorkflow.kt:316)
	at com.intellij.vcs.commit.AbstractCommitWorkflowHandler.initCommitHandlers(AbstractCommitWorkflowHandler.kt:89)
	at com.intellij.vcs.commit.NonModalCommitWorkflowHandler.vcsesChanged(NonModalCommitWorkflowHandler.kt:75)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler.<init>(ChangesViewCommitWorkflowHandler.kt:79)
	at com.intellij.openapi.vcs.changes.ChangesViewManager$ChangesViewToolWindowPanel.updateCommitWorkflow(ChangesViewManager.java:577)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.updateCommitWorkflow(ChangesViewManager.java:272)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.lambda$new$0(ChangesViewManager.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:671)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:649)
	at com.intellij.util.messages.impl.MessageBusImpl.access$300(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.executeOrAddToQueue(MessageBusImpl.java:215)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.publish(MessageBusImpl.java:197)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:181)
	at com.sun.proxy.$Proxy158.commitModeChanged(Unknown Source)
	at com.intellij.vcs.commit.CommitModeManager.updateCommitMode(CommitModeManager.kt:75)
	at com.intellij.vcs.commit.CommitModeManager$MyStartupActivity$runActivity$$inlined$runInEdt$1.run(actions.kt:64)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by thomasrepnik** [comment]
Thank you for reporting. Can you please describe how to reproduce the error? I tried it on different projects without git integration, but was not able to reproduce the error.  

Where do you see the Stacktrace? In the IntelliJ's LogFile? or is the error popping up somewhere on the UI?

**Comment by twwd** [comment]
The problem occurs if the project had `.git` initialized, but the `.git` folder was deleted and thus IntelliJ reports the following:
> **Invalid VCS root mapping**
> The directory ~/Dev/untitled is registered as a Git root, but no Git repositories were found there.

I've got the stacktrace by clicking on the following toast message:
![IDE_error_toast](https://user-images.githubusercontent.com/8222565/115344812-2f9afd00-a1ae-11eb-92c8-28e9a46c5bde.png)

Then I've got the following popup:
![IDE_error_popup](https://user-images.githubusercontent.com/8222565/115344892-4ccfcb80-a1ae-11eb-9cb0-79903f1dbd67.png)

**Comment by shoutcool** [comment]
Thank you! 👍  Will take a look

**Comment by twwd** [comment]
Thanks for the fast fix @thomasrepnik!

**Comment by thomasrepnik** [comment]
You're welcome. Thank you for reporting and explaining 👍
